spring:
  application:
    name: hystrix-dashboard-turbine
server:
  port: 8083
  address: 0.0.0.0
turbine:
  app-config: "account-service,book-service,book-show-service,config,eureka-server,index-show-service\
    inventory-service,person-service,show-aggregation-service,turbine\
    upload-service,user-service,user-show-service,zuul,order-service\
    purchase-service,logistics-service,money-service,auth-service"
  aggregator:
    cluster-config: "default"
  cluster-name-expression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.22:9000/eureka/
