server:
  port: 8099
  address: 0.0.0.0
spring:
  profiles:
    active: test
  application:
    name: auth-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.22:9000/eureka/,http://192.168.0.21:9000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
