spring:
  application:
    name: gateway-service-zuul
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
    command:
      default:
        execution:
          isolation:
            strategy: THREAD
            thread:
                 timeoutInMilliseconds: 212000

soa:
  filter:
    whitelist:
      - user-service/v1/User/login
      - auth-service/v1/User/login
      - /swagger-resources
      - /v2/api-docs
      - /swagger-ui
      - /swagger-resources
