server:
  port: 8081
  address: 0.0.0.0
spring:
  profiles:
    active: test
  application:
    name: gateway-service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.22:9000/eureka/

