server:
  port: 8091
spring:
  profiles:
    active: test
  application:
    name: user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_node2:9000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
