server:
  port: 8087
spring:
  profiles:
    active: pro
  application:
    name: inventory-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9000/eureka/,http://peer2:9000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"