server:
  port: 8080
spring:
  profiles:
    active: pro
  application:
    name: account-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.96.156.169:9000/eureka/,http://123.57.144.153:9000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"