spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 9000
  address: 0.0.0.0
eureka:
  instance:
    #要求Client通过ip的方式进行注册
    prefer-ip-address: true
    instance-id: springcloud-eurekaserver-A6-114
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-node2:9000/eureka/,http://eureka-node1:9000/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
