server:
  port: 8086
  address: 0.0.0.0
spring:
  profiles:
    active: test
  application:
    name: index-show-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-node2:9000/eureka/,http://eureka-node1:9000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
