users:
  list:
    -
      username: 'admin1'
      password: 'password'
    -
      username: 'admin2'
      password: 'password'
    -
      username: 'user1'
      password: 'password345'
    -
      username: 'user2'
      password: 'password345'