spring:
  cloud:
    config:
      name: soa-config,data
      label: master
---
spring:
  profiles:
    active: default
  cloud:
    config:
      uri: http://118.25.88.125:8002
      profile: dev
      discovery:
        enabled: false
---
spring:
  profiles:
    active: pro
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: spring-cloud-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/